CREATE TABLE IF NOT EXISTS book_categories (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    updated_at TIMESTAMP NULL 
);

CREATE TABLE IF NOT EXISTS users(
    id UUID PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    pass_hash VARCHAR(255) NOT NULL,
    access_level INT NOT NULL DEFAULT 50,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
